---
namespace: "serdigital64"
name: "development"
version: "1.3.1"
readme: "README.md"
authors:
  - "SerDigital64 <https://github.com/serdigital64>"
description: "Ansible Roles for automating development environment provisioning"
license:
  - "GPL-3.0-or-later"
tags:
  - "development"
dependencies:
  serdigital64.backup: "*"
  serdigital64.system: "*"
repository: "https://github.com/serdigital64/aplatform64"
homepage: "https://github.com/serdigital64/aplatform64"
issues: "https://github.com/serdigital64/aplatform64/issues"
documentation: "https://aplatform64.readthedocs.io"
...
