---
dev_python_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"
  - "MacOSX12"

dev_python_base_common:
  files:
    requirements_txt: "requirements.txt"
...
