---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Discover packages"
      ansible.builtin.package_facts:
        manager: "auto"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "dev_java"

    - name: "Verify required packages are deployed (package: {{ item }})"
      ansible.builtin.assert:
        that:
          - dev_java_profiles[item['key']]['distro']['latest']['packages'][0]['name'] in ansible_facts['packages']
      loop: "{{ dev_java_application | dict2items  }}"
...
