---
dev_java_application:
  openjdk_jdk_v1_8:
    name: "openjdk_jdk_v1_8"
    type: "distro"
    version: "latest"
    installed: false
  openjdk_jdk_v1_11:
    name: "openjdk_jdk_v1_11"
    type: "distro"
    version: "latest"
    installed: false
  openjdk_jdk_v1_17:
    name: "openjdk_jdk_v1_17"
    type: "distro"
    version: "latest"
    installed: true
...
