---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Provision app"
      vars:
        dev_python:
          provision: true
        dev_python_applications:
          - name: "mkdocs"
            description: "test app"
            location: "/opt/test-mkdocs"
            owner: "root"
            group: "root"
            modules:
              - "mkdocs"

      ansible.builtin.include_role:
        name: "dev_python"
...
