---
dev_java_base:
  run:
    java: "/usr/bin/java"

dev_java_profiles:
  openjdk_jdk_v1_8:
    distro:
      latest:
        packages:
          - name: "openjdk-8-jdk"
  openjdk_jdk_v1_11:
    distro:
      latest:
        packages:
          - name: "openjdk-11-jdk"
  openjdk_jdk_v1_17:
    distro:
      latest:
        packages:
          - name: "openjdk-17-jdk"

dev_java_repository_custom_yum: []
dev_java_repository_custom_apt: []

dev_java_repository_catalog_distro: {}
dev_java_repository_catalog_yum: {}
dev_java_repository_catalog_apt: {}
...
