---
- name: "Development / Java / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ dev_java___deploy_profile['value'] }}"
    sys_package_profiles: "{{
        dev_java_profiles[
          dev_java___deploy_profile['key']
        ]
      }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
